# Configuration for Apollo Router
---
sandbox:
  enabled: true
supergraph:
  listen: 0.0.0.0:4000
  introspection: true
cors:
  allow_any_origin: true
telemetry:
  tracing:
    trace_config:
      service_name: "router"
      service_namespace: "apollo"
      sampler: 1
    propagation:
      trace_context: true
    otlp:
      endpoint: "otel-collector:4317"
  metrics:
    common:
      service_name: "graphql-gateway"
    prometheus:
      enabled: true
      listen: 0.0.0.0:4000
      path: /metrics
headers:
  all:
    request:
      - propagate:
          matching: .*
